// This file is automatically generated. Do not modify it.
// For more information, see https://firebase.google.com/docs/web/learn-more#config-object

import { FirebaseOptions } from "firebase/app";

// Your web app's Firebase configuration
const firebaseConfig: FirebaseOptions = {
  apiKey: "TODO:_SET_YOUR_FIREBASE_API_KEY",
  authDomain: "TODO:your-project-id.firebaseapp.com",
  projectId: "TODO:your-project-id",
  storageBucket: "TODO:your-project-id.appspot.com",
  messagingSenderId: "TODO:your-sender-id",
  appId: "TODO:your-app-id",
};

export function getFirebaseConfig() {
  if (!firebaseConfig || !firebaseConfig.apiKey) {
    throw new Error(
      "No Firebase configuration object provided." +
        "Add your web app's configuration object to src/firebase/config.ts"
    );
  }
  return firebaseConfig;
}
